### ISSUE TITLE
Multiple bundles are included in dev mode.

### ISSUE THREAD

**Issue by msegers** [firsttris/html-webpack-multi-build-plugin#3]
As noted in #1 after rebuilds when using hashes in filenames (chunk hashes). The dev mode will include multiple main bundles. This obviously brings forward some issues.

I'm not entirely sure how to fix, as clearing pre-emit sometimes results in only one bundle to remain (and possibly only legacy so whitespace etc.).

A possibility, though seems flaky, would be to filter the stored files (in the plugins js array) based on the incoming files. Possibly we can get the entry point filename(s) and make sure we only keep the latest?

Better ideas welcome.

I was not able to find specific Multi compiler hooks, also clearing the js array is tricky if something goes wrong during the build as you'll only have the singular js file and potentially white pages.

**Comment by firsttris** [comment]
actually we did not use this multi build for DEV we have 2 different dev jobs for modern & legacy.

but i find this idea interesting
